linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
